services:
  - type: web
    name: resistance-server
    runtime: node            # (you can keep env: node, but runtime is the new field)
    rootDirectory: server
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /
    plan: free
    autoDeploy: true

  - type: web
    name: resistance-client
    runtime: static          # <-- static site
    rootDirectory: client
    buildCommand: ""         # no build step
    publishPath: .           # serve the files in /client
    plan: free
    autoDeploy: true
