services:
  # Node Web Service (the realtime game server)
  - type: web
    name: resistance-server
    runtime: node
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /
    plan: free
    autoDeployTrigger: commit

  # Static Site (the PWA client)
  - type: web
    name: resistance-client
    runtime: static
    # staticPublishPath is ALWAYS relative to the repo root
    staticPublishPath: ./client
    buildCommand: ""       # no build step
    plan: free
    autoDeployTrigger: commit
