services:
  # Node Web Service (realtime server)
  - type: web
    name: resistance-server
    runtime: node
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /
    autoDeployTrigger: commit
    plan: free   # ok for web services

  # Static Site (PWA client)
  - type: web
    name: resistance-client
    runtime: static
    staticPublishPath: ./client   # folder to serve (relative to repo root)
    buildCommand: ""              # no build step; remove this line if Render complains
    autoDeployTrigger: commit
