services:
  - type: web
    name: resistance-server
    env: node
    rootDirectory: server
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /
    plan: free
    autoDeploy: true

  - type: static_site
    name: resistance-client
    rootDirectory: client
    buildCommand: ""
    publishPath: .
    autoDeploy: true
